utest failure: <lambda>
  arg 0=0
  arg 1=1
  arg x='x'
  arg y='y'
  expected value: True
  returned value: False

utest failure: raise_unexpected
  expected value: True
  raised exception: Exception('unexpected',)

utest failure: <lambda>
  expected exception: Exception('expected',)
  returned value: True

utest failure: raise_unexpected
  expected exception: Exception('expected',)
  raised exception: Exception('unexpected',)

