| iotest: DEBUG MODE ON.
|
| Case:
|   args: None
|   broken: False
|   cmd: 'false'
|   code: None
|   compile: None
|   compile_cmds: []
|   compile_timeout: None
|   coverage: None
|   coverage_targets: []
|   desc: None
|   dflt_src_path: None
|   env: None
|   err_mode: None
|   err_path: None
|   err_val: None
|   files: None
|   in_: None
|   links: None
|   name: 'fail-dbg'
|   out_mode: None
|   out_path: None
|   out_val: None
|   skip: None
|   stem: 'test-meta/fail-dbg'
|   test_cmd: ['false']
|   test_dir: '/Users/gwk/work/iotest/_build/test-meta/fail-dbg'
|   test_env: {'BUILD':'/Users/gwk/work/iotest/_build', 'NAME':'fail-dbg', 'PATH':'/usr/local/gloss/bin:/usr/local/cmake/bin:/usr/local/git/bin:/usr/local/graphviz/bin:/usr/local/heroku/bin:/usr/local/llvm/3.8.0/bin:/usr/local/nasm/bin:/usr/local/py/bin:/usr/local/ruby/bin:/usr/local/rust/bin:/usr/local/turbojpeg/bin:/usr/local/xctool/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'PROJ':'/Users/gwk/work/iotest', 'SDKROOT':'/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk', 'SRC':'None', 'STEM':'test-meta/fail-dbg'}
|   test_expectations: [FileExpectation('err', 'equal', ''), FileExpectation('out', 'equal', '')]
|   test_in: None
|   test_info_paths: ['test-meta/fail-dbg.iot']
|   test_links: []
|   timeout: None
| input path: /dev/null
| test cwd: /Users/gwk/work/iotest/_build/test-meta/fail-dbg
| test cmd: false </dev/null # 1>/Users/gwk/work/iotest/_build/test-meta/fail-dbg/out 2>/Users/gwk/work/iotest/_build/test-meta/fail-dbg/err
| check_file_exp: FileExpectation('err', 'equal', '')
| check_file_exp: FileExpectation('out', 'equal', '')
|
| iotest: stopping after error (-fail-fast).
